//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * 
 * 				A ViewForm defines a responsible java class for each supported view form (environment) type. Depending on layout of parent
 * 				conatiner for a stand alone application this will be an extension of JFrame, JPanel, JInternalFrame or JDialog. If a view form is
 * 				embedded as a JPanel attributes useVerticalScrollBar and useHorizontalScrollBar can be used to define that scrollbars should
 * 				be used if size of a view form exeeds available space within its container.
 * 			
 * 
 * <p>Java class for _AbstractViewFormType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_AbstractViewFormType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="containerClass" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="viewPlatform" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.deegree.org/project}ComponentState"/>
 *         &lt;element name="MenuBar" type="{http://www.deegree.org/project}MenuBarType" minOccurs="0"/>
 *         &lt;element name="PopUpMenu" type="{http://www.deegree.org/project}PopUpMenuType" minOccurs="0"/>
 *         &lt;element name="ToolBar" type="{http://www.deegree.org/project}ToolbarType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="useVerticalScrollBar" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="useHorizontalScrollBar" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_AbstractViewFormType", propOrder = {
    "containerClass",
    "componentState",
    "menuBar",
    "popUpMenu",
    "toolBar"
})
@XmlSeeAlso({
    PaneViewFormType.class,
    InnerFrameViewFormType.class,
    FrameViewFormType.class
})
public abstract class _AbstractViewFormType {

    protected List<_AbstractViewFormType.ContainerClass> containerClass;
    @XmlElement(name = "ComponentState", required = true)
    protected ComponentStateType componentState;
    @XmlElement(name = "MenuBar")
    protected MenuBarType menuBar;
    @XmlElement(name = "PopUpMenu")
    protected PopUpMenuType popUpMenu;
    @XmlElement(name = "ToolBar")
    protected List<ToolbarType> toolBar;
    @XmlAttribute
    protected Boolean useVerticalScrollBar;
    @XmlAttribute
    protected Boolean useHorizontalScrollBar;

    /**
     * Gets the value of the containerClass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the containerClass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContainerClass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link _AbstractViewFormType.ContainerClass }
     * 
     * 
     */
    public List<_AbstractViewFormType.ContainerClass> getContainerClass() {
        if (containerClass == null) {
            containerClass = new ArrayList<_AbstractViewFormType.ContainerClass>();
        }
        return this.containerClass;
    }

    /**
     * Gets the value of the componentState property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentStateType }
     *     
     */
    public ComponentStateType getComponentState() {
        return componentState;
    }

    /**
     * Sets the value of the componentState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentStateType }
     *     
     */
    public void setComponentState(ComponentStateType value) {
        this.componentState = value;
    }

    /**
     * Gets the value of the menuBar property.
     * 
     * @return
     *     possible object is
     *     {@link MenuBarType }
     *     
     */
    public MenuBarType getMenuBar() {
        return menuBar;
    }

    /**
     * Sets the value of the menuBar property.
     * 
     * @param value
     *     allowed object is
     *     {@link MenuBarType }
     *     
     */
    public void setMenuBar(MenuBarType value) {
        this.menuBar = value;
    }

    /**
     * Gets the value of the popUpMenu property.
     * 
     * @return
     *     possible object is
     *     {@link PopUpMenuType }
     *     
     */
    public PopUpMenuType getPopUpMenu() {
        return popUpMenu;
    }

    /**
     * Sets the value of the popUpMenu property.
     * 
     * @param value
     *     allowed object is
     *     {@link PopUpMenuType }
     *     
     */
    public void setPopUpMenu(PopUpMenuType value) {
        this.popUpMenu = value;
    }

    /**
     * Gets the value of the toolBar property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toolBar property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToolBar().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ToolbarType }
     * 
     * 
     */
    public List<ToolbarType> getToolBar() {
        if (toolBar == null) {
            toolBar = new ArrayList<ToolbarType>();
        }
        return this.toolBar;
    }

    /**
     * Gets the value of the useVerticalScrollBar property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseVerticalScrollBar() {
        if (useVerticalScrollBar == null) {
            return false;
        } else {
            return useVerticalScrollBar;
        }
    }

    /**
     * Sets the value of the useVerticalScrollBar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseVerticalScrollBar(Boolean value) {
        this.useVerticalScrollBar = value;
    }

    /**
     * Gets the value of the useHorizontalScrollBar property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseHorizontalScrollBar() {
        if (useHorizontalScrollBar == null) {
            return false;
        } else {
            return useHorizontalScrollBar;
        }
    }

    /**
     * Sets the value of the useHorizontalScrollBar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseHorizontalScrollBar(Boolean value) {
        this.useHorizontalScrollBar = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="viewPlatform" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ContainerClass {

        @XmlValue
        protected String value;
        @XmlAttribute(required = true)
        protected String viewPlatform;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the viewPlatform property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getViewPlatform() {
            return viewPlatform;
        }

        /**
         * Sets the value of the viewPlatform property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setViewPlatform(String value) {
            this.viewPlatform = value;
        }

    }

}
