//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Each layer must have 1..n datasources. All concrete datasource definitions must extend the AbstractDatasource which defines
 * 				several elements that common to all types of datasources.
 * 				- name: each datasource must have a name. It is strongly recommented to use unique names
 * 				- extent: defines the spatial extent for which a datasource is valid.
 * 				- nativeCRS: code of the coordinate reference system the data provided a datasource are stored (the code must be known by deegree)
 * 				- minScaleDenominator/maxScaleDenominator: scale range a datasource is valid. ScaleDenominators are defined like specified by
 * 				  OGC SLD 1.0.0 Specification
 * 				- authenticationInformation: If a user authentication is required for accessing a datasource, authentication type and paramters to be used 
 * 				  for authentication can be defined here (not supported at the moment)
 * 				- cache: specifies what kind of cache should be used for a datasource (not supported at the moment)
 * 				- referenceProperty: Especially for vector and WMS datasources it is possible to define on or more properties/attributes of the provided
 * 				  data that contains references to resources like officedocuments, images or HTML pages the can be used open a assigned program
 * 				  automaticliy if a feature/object info action if perfromed on such an object.
 * 				- layzLoading: if set to true data will just be read from underlying backend if requested (not supported at the moment)
 * 				- queryable: if set to true a datasource will be considered if a feature/object info action if perfromed 
 * 				- editable: if set to true data provided by a datasource can be edited (insert/update/delete)
 * 				- supportToolTips: if set to true info about features/objects will be opened on mouse over events (not supported at the moment)
 * 			
 * 
 * <p>Java class for AbstractDatasourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractDatasourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.deegree.org/coremapmodel}extent"/>
 *         &lt;element name="nativeCRS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="minScaleDenominator" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="maxScaleDenominator" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="authenticationInformation" type="{http://www.deegree.org/coremapmodel}AuthenticationInformationType" minOccurs="0"/>
 *         &lt;element name="cache" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="referenceProperty" type="{http://www.deegree.org/coremapmodel}QualifiedNameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/coremapmodel}AbstractLinkedTable" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="lazyLoading" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="queryable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="supportToolTips" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractDatasourceType", namespace = "http://www.deegree.org/coremapmodel", propOrder = {
    "name",
    "extent",
    "nativeCRS",
    "minScaleDenominator",
    "maxScaleDenominator",
    "authenticationInformation",
    "cache",
    "referenceProperty",
    "abstractLinkedTable"
})
@XmlSeeAlso({
    ServiceDatasourceType.class,
    DatabaseDatasourceType.class,
    MemoryDatasourceType.class,
    FileDatasourceType.class
})
public abstract class AbstractDatasourceType {

    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected String name;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected EnvelopeType extent;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected String nativeCRS;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", defaultValue = "0")
    protected Double minScaleDenominator;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", defaultValue = "99999999")
    protected Double maxScaleDenominator;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel")
    protected AuthenticationInformationType authenticationInformation;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel")
    protected String cache;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel")
    protected List<QualifiedNameType> referenceProperty;
    @XmlElementRef(name = "AbstractLinkedTable", namespace = "http://www.deegree.org/coremapmodel", type = JAXBElement.class)
    protected List<JAXBElement<? extends AbstractLinkedTableType>> abstractLinkedTable;
    @XmlAttribute
    protected Boolean lazyLoading;
    @XmlAttribute
    protected Boolean queryable;
    @XmlAttribute
    protected Boolean editable;
    @XmlAttribute
    protected Boolean supportToolTips;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the extent property.
     * 
     * @return
     *     possible object is
     *     {@link EnvelopeType }
     *     
     */
    public EnvelopeType getExtent() {
        return extent;
    }

    /**
     * Sets the value of the extent property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnvelopeType }
     *     
     */
    public void setExtent(EnvelopeType value) {
        this.extent = value;
    }

    /**
     * Gets the value of the nativeCRS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNativeCRS() {
        return nativeCRS;
    }

    /**
     * Sets the value of the nativeCRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNativeCRS(String value) {
        this.nativeCRS = value;
    }

    /**
     * Gets the value of the minScaleDenominator property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinScaleDenominator() {
        return minScaleDenominator;
    }

    /**
     * Sets the value of the minScaleDenominator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinScaleDenominator(Double value) {
        this.minScaleDenominator = value;
    }

    /**
     * Gets the value of the maxScaleDenominator property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxScaleDenominator() {
        return maxScaleDenominator;
    }

    /**
     * Sets the value of the maxScaleDenominator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxScaleDenominator(Double value) {
        this.maxScaleDenominator = value;
    }

    /**
     * Gets the value of the authenticationInformation property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationInformationType }
     *     
     */
    public AuthenticationInformationType getAuthenticationInformation() {
        return authenticationInformation;
    }

    /**
     * Sets the value of the authenticationInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationInformationType }
     *     
     */
    public void setAuthenticationInformation(AuthenticationInformationType value) {
        this.authenticationInformation = value;
    }

    /**
     * Gets the value of the cache property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCache() {
        return cache;
    }

    /**
     * Sets the value of the cache property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCache(String value) {
        this.cache = value;
    }

    /**
     * Gets the value of the referenceProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenceProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenceProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualifiedNameType }
     * 
     * 
     */
    public List<QualifiedNameType> getReferenceProperty() {
        if (referenceProperty == null) {
            referenceProperty = new ArrayList<QualifiedNameType>();
        }
        return this.referenceProperty;
    }

    /**
     * Gets the value of the abstractLinkedTable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the abstractLinkedTable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAbstractLinkedTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link LinkedDatabaseTableType }{@code >}
     * {@link JAXBElement }{@code <}{@link AbstractLinkedTableType }{@code >}
     * {@link JAXBElement }{@code <}{@link LinkedFileTableType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends AbstractLinkedTableType>> getAbstractLinkedTable() {
        if (abstractLinkedTable == null) {
            abstractLinkedTable = new ArrayList<JAXBElement<? extends AbstractLinkedTableType>>();
        }
        return this.abstractLinkedTable;
    }

    /**
     * Gets the value of the lazyLoading property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLazyLoading() {
        if (lazyLoading == null) {
            return false;
        } else {
            return lazyLoading;
        }
    }

    /**
     * Sets the value of the lazyLoading property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLazyLoading(Boolean value) {
        this.lazyLoading = value;
    }

    /**
     * Gets the value of the queryable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isQueryable() {
        if (queryable == null) {
            return false;
        } else {
            return queryable;
        }
    }

    /**
     * Sets the value of the queryable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setQueryable(Boolean value) {
        this.queryable = value;
    }

    /**
     * Gets the value of the editable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEditable() {
        if (editable == null) {
            return false;
        } else {
            return editable;
        }
    }

    /**
     * Sets the value of the editable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEditable(Boolean value) {
        this.editable = value;
    }

    /**
     * Gets the value of the supportToolTips property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSupportToolTips() {
        if (supportToolTips == null) {
            return false;
        } else {
            return supportToolTips;
        }
    }

    /**
     * Sets the value of the supportToolTips property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSupportToolTips(Boolean value) {
        this.supportToolTips = value;
    }

}
