//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				For user specific color schemes:
 *                  - Colorlist/OnlineResource: direct or external reference to a list of colors representing the color schema 
 *                  - name: unique name of the color list (displayed in the selection list)
 * 			
 * 
 * <p>Java class for ColorSchemesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ColorSchemesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Colorlist" type="{http://www.deegree.org/settings}ColorListType"/>
 *         &lt;element ref="{http://www.deegree.org/coremapmodel}OnlineResource"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ColorSchemesType", namespace = "http://www.deegree.org/settings", propOrder = {
    "colorlist",
    "onlineResource"
})
public class ColorSchemesType {

    @XmlElement(name = "Colorlist", namespace = "http://www.deegree.org/settings")
    protected ColorListType colorlist;
    @XmlElement(name = "OnlineResource", namespace = "http://www.deegree.org/coremapmodel")
    protected OnlineResourceType onlineResource;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the colorlist property.
     * 
     * @return
     *     possible object is
     *     {@link ColorListType }
     *     
     */
    public ColorListType getColorlist() {
        return colorlist;
    }

    /**
     * Sets the value of the colorlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorListType }
     *     
     */
    public void setColorlist(ColorListType value) {
        this.colorlist = value;
    }

    /**
     * Gets the value of the onlineResource property.
     * 
     * @return
     *     possible object is
     *     {@link OnlineResourceType }
     *     
     */
    public OnlineResourceType getOnlineResource() {
        return onlineResource;
    }

    /**
     * Sets the value of the onlineResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnlineResourceType }
     *     
     */
    public void setOnlineResource(OnlineResourceType value) {
        this.onlineResource = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
