//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Through this element GML dictionaries can be registered to use predefined lists instead of free text entries for editing feature properties
 * 				and creating a WFS GetFeature query
 * 			
 * 
 * <p>Java class for DictionariesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DictionariesType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/settings}_ChangeableType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.deegree.org/coremapmodel}OnlineResource" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DictionariesType", namespace = "http://www.deegree.org/settings", propOrder = {
    "onlineResource"
})
public class DictionariesType
    extends _ChangeableType
{

    @XmlElement(name = "OnlineResource", namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected List<OnlineResourceType> onlineResource;

    /**
     * Gets the value of the onlineResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onlineResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnlineResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnlineResourceType }
     * 
     * 
     */
    public List<OnlineResourceType> getOnlineResource() {
        if (onlineResource == null) {
            onlineResource = new ArrayList<OnlineResourceType>();
        }
        return this.onlineResource;
    }

}
