//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for EntryValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EntryValueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SimpleItem"/>
 *     &lt;enumeration value="RadioButtonItem"/>
 *     &lt;enumeration value="CheckBoxItem"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum EntryValueType {

    @XmlEnumValue("SimpleItem")
    SIMPLE_ITEM("SimpleItem"),
    @XmlEnumValue("RadioButtonItem")
    RADIO_BUTTON_ITEM("RadioButtonItem"),
    @XmlEnumValue("CheckBoxItem")
    CHECK_BOX_ITEM("CheckBoxItem");
    private final String value;

    EntryValueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EntryValueType fromValue(String v) {
        for (EntryValueType c: EntryValueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
