//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeometryTopologyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeometryTopologyType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/settings}_ChangeableType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="allowIntersection" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="allowTouching" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="allowEqualGeometries" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeometryTopologyType", namespace = "http://www.deegree.org/settings")
public class GeometryTopologyType
    extends _ChangeableType
{

    @XmlAttribute
    protected Boolean allowIntersection;
    @XmlAttribute
    protected Boolean allowTouching;
    @XmlAttribute
    protected Boolean allowEqualGeometries;

    /**
     * Gets the value of the allowIntersection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowIntersection() {
        if (allowIntersection == null) {
            return false;
        } else {
            return allowIntersection;
        }
    }

    /**
     * Sets the value of the allowIntersection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowIntersection(Boolean value) {
        this.allowIntersection = value;
    }

    /**
     * Gets the value of the allowTouching property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowTouching() {
        if (allowTouching == null) {
            return true;
        } else {
            return allowTouching;
        }
    }

    /**
     * Sets the value of the allowTouching property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowTouching(Boolean value) {
        this.allowTouching = value;
    }

    /**
     * Gets the value of the allowEqualGeometries property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowEqualGeometries() {
        if (allowEqualGeometries == null) {
            return false;
        } else {
            return allowEqualGeometries;
        }
    }

    /**
     * Sets the value of the allowEqualGeometries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowEqualGeometries(Boolean value) {
        this.allowEqualGeometries = value;
    }

}
