//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				view form definition for displaying a module within window contained in an internal frame container (parent must offer this)
 * 				 A window may be set to be resizeable or not
 * 			
 * 
 * <p>Java class for InnerFrameViewFormType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InnerFrameViewFormType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/project}_AbstractViewFormType">
 *       &lt;sequence>
 *         &lt;element name="frameTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="resizeable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InnerFrameViewFormType", propOrder = {
    "frameTitle"
})
public class InnerFrameViewFormType
    extends _AbstractViewFormType
{

    @XmlElement(required = true)
    protected String frameTitle;
    @XmlAttribute
    protected Boolean resizeable;

    /**
     * Gets the value of the frameTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameTitle() {
        return frameTitle;
    }

    /**
     * Sets the value of the frameTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameTitle(String value) {
        this.frameTitle = value;
    }

    /**
     * Gets the value of the resizeable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isResizeable() {
        if (resizeable == null) {
            return true;
        } else {
            return resizeable;
        }
    }

    /**
     * Sets the value of the resizeable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setResizeable(Boolean value) {
        this.resizeable = value;
    }

}
