//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LayoutType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LayoutType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.deegree.org/project}_AbstractLayout"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LayoutType", propOrder = {
    "abstractLayout"
})
public class LayoutType {

    @XmlElementRef(name = "_AbstractLayout", namespace = "http://www.deegree.org/project", type = JAXBElement.class)
    protected JAXBElement<? extends _AbstractLayoutType> abstractLayout;

    /**
     * Gets the value of the _AbstractLayout property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link NoneLayoutType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GridLayoutType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SplittedLayoutType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BorderLayoutType }{@code >}
     *     {@link JAXBElement }{@code <}{@link _AbstractLayoutType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TabLayoutType }{@code >}
     *     
     */
    public JAXBElement<? extends _AbstractLayoutType> get_AbstractLayout() {
        return abstractLayout;
    }

    /**
     * Sets the value of the _AbstractLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link NoneLayoutType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GridLayoutType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SplittedLayoutType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BorderLayoutType }{@code >}
     *     {@link JAXBElement }{@code <}{@link _AbstractLayoutType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TabLayoutType }{@code >}
     *     
     */
    public void set_AbstractLayout(JAXBElement<? extends _AbstractLayoutType> value) {
        this.abstractLayout = ((JAXBElement<? extends _AbstractLayoutType> ) value);
    }

}
