//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LinkedDatabaseTableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LinkedDatabaseTableType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/coremapmodel}AbstractLinkedTableType">
 *       &lt;sequence>
 *         &lt;element name="connection" type="{http://www.deegree.org/jdbc}JDBCConnectionType"/>
 *         &lt;element name="sqlTemplate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LinkedDatabaseTableType", namespace = "http://www.deegree.org/coremapmodel", propOrder = {
    "connection",
    "sqlTemplate"
})
public class LinkedDatabaseTableType
    extends AbstractLinkedTableType
{

    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected JDBCConnectionType connection;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected String sqlTemplate;

    /**
     * Gets the value of the connection property.
     * 
     * @return
     *     possible object is
     *     {@link JDBCConnectionType }
     *     
     */
    public JDBCConnectionType getConnection() {
        return connection;
    }

    /**
     * Sets the value of the connection property.
     * 
     * @param value
     *     allowed object is
     *     {@link JDBCConnectionType }
     *     
     */
    public void setConnection(JDBCConnectionType value) {
        this.connection = value;
    }

    /**
     * Gets the value of the sqlTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqlTemplate() {
        return sqlTemplate;
    }

    /**
     * Sets the value of the sqlTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqlTemplate(String value) {
        this.sqlTemplate = value;
    }

}
