//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				A project in iGeodesktop must contain a MapModelCollection. As its name says a MapModelCollection contains 1..n MapModels. A MapModelCollection
 * 				itself has a name and a maximum spatial extent. It may has a description and references to external documents like Excel sheets or Offices documents
 * 				that contains more detailed description of the data/layers gathered in a MapModelCollection
 * 			
 * 
 * <p>Java class for MapModelCollectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MapModelCollectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.deegree.org/coremapmodel}maxExtent"/>
 *         &lt;element ref="{http://www.deegree.org/coremapmodel}externalResource" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/coremapmodel}mapModel" maxOccurs="unbounded"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MapModelCollectionType", namespace = "http://www.deegree.org/coremapmodel", propOrder = {
    "name",
    "maxExtent",
    "externalResource",
    "mapModel",
    "description"
})
public class MapModelCollectionType {

    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected String name;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected EnvelopeType maxExtent;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel")
    protected List<ExternalResourceType> externalResource;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected List<MapModelType> mapModel;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel")
    protected String description;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the maxExtent property.
     * 
     * @return
     *     possible object is
     *     {@link EnvelopeType }
     *     
     */
    public EnvelopeType getMaxExtent() {
        return maxExtent;
    }

    /**
     * Sets the value of the maxExtent property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnvelopeType }
     *     
     */
    public void setMaxExtent(EnvelopeType value) {
        this.maxExtent = value;
    }

    /**
     * Gets the value of the externalResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalResourceType }
     * 
     * 
     */
    public List<ExternalResourceType> getExternalResource() {
        if (externalResource == null) {
            externalResource = new ArrayList<ExternalResourceType>();
        }
        return this.externalResource;
    }

    /**
     * Gets the value of the mapModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mapModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMapModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MapModelType }
     * 
     * 
     */
    public List<MapModelType> getMapModel() {
        if (mapModel == null) {
            mapModel = new ArrayList<MapModelType>();
        }
        return this.mapModel;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
