//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Two or more modules can be arranged within a modulegroup. The way how the modules are arranged (TabLayout, Splitter, Grid ...) depends
 * 				on layout definition of the parent module.
 * 			
 * 
 * <p>Java class for ModuleGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModuleGroupType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/project}ModuleType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.deegree.org/project}ModuleRegister" maxOccurs="unbounded" minOccurs="2"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModuleGroupType", propOrder = {
    "moduleRegister"
})
public class ModuleGroupType
    extends ModuleType
{

    @XmlElement(name = "ModuleRegister", required = true)
    protected List<ModuleRegisterType> moduleRegister;

    /**
     * Gets the value of the moduleRegister property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the moduleRegister property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModuleRegister().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModuleRegisterType }
     * 
     * 
     */
    public List<ModuleRegisterType> getModuleRegister() {
        if (moduleRegister == null) {
            moduleRegister = new ArrayList<ModuleRegisterType>();
        }
        return this.moduleRegister;
    }

}
