//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				A ModuleRegister enables registering modules to a project or as sub-modules to other modules. So enhanced GUIs can be constructed.
 * 				A registered module can be a simple module or a module group where 2..n modules are arranged in a defined layout contained (e.g. a grid).
 * 				Modules can be defined diretly embadding a complete module description or be referenced by an absolute or relative path. For each registered
 * 				module its postion within a projects GUI will be defined by extensions of a abstract element _ComponentPosition. Valid concrete types/elements
 * 				depends on layout container of parent module/application.
 * 			
 * 
 * <p>Java class for ModuleRegisterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModuleRegisterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element ref="{http://www.deegree.org/project}_ComponentPosition"/>
 *         &lt;/sequence>
 *         &lt;choice>
 *           &lt;element name="ModuleReference">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{http://www.deegree.org/coremapmodel}OnlineResource"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element ref="{http://www.deegree.org/project}Module"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModuleRegisterType", propOrder = {
    "componentPosition",
    "moduleReference",
    "module"
})
public class ModuleRegisterType {

    @XmlElementRef(name = "_ComponentPosition", namespace = "http://www.deegree.org/project", type = JAXBElement.class)
    protected JAXBElement<? extends _ComponentPositionType> componentPosition;
    @XmlElement(name = "ModuleReference")
    protected ModuleRegisterType.ModuleReference moduleReference;
    @XmlElementRef(name = "Module", namespace = "http://www.deegree.org/project", type = JAXBElement.class)
    protected JAXBElement<? extends ModuleType> module;

    /**
     * Gets the value of the _ComponentPosition property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BorderPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SplitterPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TabPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link _ComponentPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link HeaderPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FooterPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GridPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbsolutePositionType }{@code >}
     *     
     */
    public JAXBElement<? extends _ComponentPositionType> get_ComponentPosition() {
        return componentPosition;
    }

    /**
     * Sets the value of the _ComponentPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BorderPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SplitterPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TabPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link _ComponentPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link HeaderPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FooterPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GridPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbsolutePositionType }{@code >}
     *     
     */
    public void set_ComponentPosition(JAXBElement<? extends _ComponentPositionType> value) {
        this.componentPosition = ((JAXBElement<? extends _ComponentPositionType> ) value);
    }

    /**
     * Gets the value of the moduleReference property.
     * 
     * @return
     *     possible object is
     *     {@link ModuleRegisterType.ModuleReference }
     *     
     */
    public ModuleRegisterType.ModuleReference getModuleReference() {
        return moduleReference;
    }

    /**
     * Sets the value of the moduleReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModuleRegisterType.ModuleReference }
     *     
     */
    public void setModuleReference(ModuleRegisterType.ModuleReference value) {
        this.moduleReference = value;
    }

    /**
     * Gets the value of the module property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ModuleType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ModuleGroupType }{@code >}
     *     
     */
    public JAXBElement<? extends ModuleType> getModule() {
        return module;
    }

    /**
     * Sets the value of the module property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ModuleType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ModuleGroupType }{@code >}
     *     
     */
    public void setModule(JAXBElement<? extends ModuleType> value) {
        this.module = ((JAXBElement<? extends ModuleType> ) value);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.deegree.org/coremapmodel}OnlineResource"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "onlineResource"
    })
    public static class ModuleReference {

        @XmlElement(name = "OnlineResource", namespace = "http://www.deegree.org/coremapmodel", required = true)
        protected OnlineResourceType onlineResource;

        /**
         * Gets the value of the onlineResource property.
         * 
         * @return
         *     possible object is
         *     {@link OnlineResourceType }
         *     
         */
        public OnlineResourceType getOnlineResource() {
            return onlineResource;
        }

        /**
         * Sets the value of the onlineResource property.
         * 
         * @param value
         *     allowed object is
         *     {@link OnlineResourceType }
         *     
         */
        public void setOnlineResource(OnlineResourceType value) {
            this.onlineResource = value;
        }

    }

}
