//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				A named style must have a name and a title; it may is described more in detail by a short abstract. If more than one
 * 				style is assigend to a layer the attribute current defines which of theses styles will be used. A named style can be used
 * 				for WMS based layers because no rendering/styling informations must be known because redering is done by connected
 * 				WMS.
 * 				Each style must know its legend representation. This can be done by referencing an image or by including a base64
 * 				encoded version of the legend directly.
 * 			
 * 
 * <p>Java class for NamedStyleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NamedStyleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="abstract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="legendURL">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{http://www.deegree.org/coremapmodel}OnlineResource"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="legendImage" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="current" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NamedStyleType", namespace = "http://www.deegree.org/coremapmodel", propOrder = {
    "name",
    "title",
    "_abstract",
    "legendURL",
    "legendImage"
})
@XmlSeeAlso({
    DefinedStyleType.class
})
public class NamedStyleType {

    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected String name;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected String title;
    @XmlElement(name = "abstract", namespace = "http://www.deegree.org/coremapmodel")
    protected String _abstract;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel")
    protected NamedStyleType.LegendURL legendURL;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel")
    protected byte[] legendImage;
    @XmlAttribute
    protected Boolean current;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbstract(String value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the legendURL property.
     * 
     * @return
     *     possible object is
     *     {@link NamedStyleType.LegendURL }
     *     
     */
    public NamedStyleType.LegendURL getLegendURL() {
        return legendURL;
    }

    /**
     * Sets the value of the legendURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedStyleType.LegendURL }
     *     
     */
    public void setLegendURL(NamedStyleType.LegendURL value) {
        this.legendURL = value;
    }

    /**
     * Gets the value of the legendImage property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLegendImage() {
        return legendImage;
    }

    /**
     * Sets the value of the legendImage property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLegendImage(byte[] value) {
        this.legendImage = ((byte[]) value);
    }

    /**
     * Gets the value of the current property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCurrent() {
        if (current == null) {
            return false;
        } else {
            return current;
        }
    }

    /**
     * Sets the value of the current property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCurrent(Boolean value) {
        this.current = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.deegree.org/coremapmodel}OnlineResource"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "onlineResource"
    })
    public static class LegendURL {

        @XmlElement(name = "OnlineResource", namespace = "http://www.deegree.org/coremapmodel", required = true)
        protected OnlineResourceType onlineResource;

        /**
         * Gets the value of the onlineResource property.
         * 
         * @return
         *     possible object is
         *     {@link OnlineResourceType }
         *     
         */
        public OnlineResourceType getOnlineResource() {
            return onlineResource;
        }

        /**
         * Sets the value of the onlineResource property.
         * 
         * @param value
         *     allowed object is
         *     {@link OnlineResourceType }
         *     
         */
        public void setOnlineResource(OnlineResourceType value) {
            this.onlineResource = value;
        }

    }

}
