//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				For each layer that is defined as snapping target it can be defined what kind of snapping it is sensible for.
 * 				At least one type must be selected (true)
 * 			
 * 
 * <p>Java class for SnapLayerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SnapLayerType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/settings}_ChangeableType">
 *       &lt;sequence>
 *         &lt;element name="layer" type="{http://www.deegree.org/coremapmodel}IdentifierType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="vertex" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="startNode" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="endNode" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="edge" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="edgeCenter" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SnapLayerType", namespace = "http://www.deegree.org/settings", propOrder = {
    "layer"
})
public class SnapLayerType
    extends _ChangeableType
{

    @XmlElement(namespace = "http://www.deegree.org/settings", required = true)
    protected IdentifierType layer;
    @XmlAttribute
    protected Boolean vertex;
    @XmlAttribute
    protected Boolean startNode;
    @XmlAttribute
    protected Boolean endNode;
    @XmlAttribute
    protected Boolean edge;
    @XmlAttribute
    protected Boolean edgeCenter;

    /**
     * Gets the value of the layer property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getLayer() {
        return layer;
    }

    /**
     * Sets the value of the layer property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setLayer(IdentifierType value) {
        this.layer = value;
    }

    /**
     * Gets the value of the vertex property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isVertex() {
        if (vertex == null) {
            return true;
        } else {
            return vertex;
        }
    }

    /**
     * Sets the value of the vertex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVertex(Boolean value) {
        this.vertex = value;
    }

    /**
     * Gets the value of the startNode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isStartNode() {
        if (startNode == null) {
            return false;
        } else {
            return startNode;
        }
    }

    /**
     * Sets the value of the startNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStartNode(Boolean value) {
        this.startNode = value;
    }

    /**
     * Gets the value of the endNode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEndNode() {
        if (endNode == null) {
            return false;
        } else {
            return endNode;
        }
    }

    /**
     * Sets the value of the endNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEndNode(Boolean value) {
        this.endNode = value;
    }

    /**
     * Gets the value of the edge property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEdge() {
        if (edge == null) {
            return false;
        } else {
            return edge;
        }
    }

    /**
     * Sets the value of the edge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEdge(Boolean value) {
        this.edge = value;
    }

    /**
     * Gets the value of the edgeCenter property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEdgeCenter() {
        if (edgeCenter == null) {
            return false;
        } else {
            return edgeCenter;
        }
    }

    /**
     * Sets the value of the edgeCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEdgeCenter(Boolean value) {
        this.edgeCenter = value;
    }

}
