//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Contretisation of _ComponentPosition for locating modules in a SplitterLayout
 * 			
 * 
 * <p>Java class for SplitterPositionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SplitterPositionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/project}_ComponentPositionType">
 *       &lt;sequence>
 *         &lt;element name="splitterPosition" type="{http://www.deegree.org/project}SplitterPositionValueType"/>
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SplitterPositionType", propOrder = {
    "splitterPosition",
    "size"
})
public class SplitterPositionType
    extends _ComponentPositionType
{

    @XmlElement(required = true)
    protected SplitterPositionValueType splitterPosition;
    protected String size;

    /**
     * Gets the value of the splitterPosition property.
     * 
     * @return
     *     possible object is
     *     {@link SplitterPositionValueType }
     *     
     */
    public SplitterPositionValueType getSplitterPosition() {
        return splitterPosition;
    }

    /**
     * Sets the value of the splitterPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link SplitterPositionValueType }
     *     
     */
    public void setSplitterPosition(SplitterPositionValueType value) {
        this.splitterPosition = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSize(String value) {
        this.size = value;
    }

}
