//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				A style basicly is a named style. All other styles are derived from this.
 * 			
 * 
 * <p>Java class for StyleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StyleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.deegree.org/coremapmodel}NamedStyle"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StyleType", namespace = "http://www.deegree.org/coremapmodel", propOrder = {
    "namedStyle"
})
public class StyleType {

    @XmlElementRef(name = "NamedStyle", namespace = "http://www.deegree.org/coremapmodel", type = JAXBElement.class)
    protected JAXBElement<? extends NamedStyleType> namedStyle;

    /**
     * Gets the value of the namedStyle property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DirectStyleType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NamedStyleType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DefinedStyleType }{@code >}
     *     
     */
    public JAXBElement<? extends NamedStyleType> getNamedStyle() {
        return namedStyle;
    }

    /**
     * Sets the value of the namedStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DirectStyleType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NamedStyleType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DefinedStyleType }{@code >}
     *     
     */
    public void setNamedStyle(JAXBElement<? extends NamedStyleType> value) {
        this.namedStyle = ((JAXBElement<? extends NamedStyleType> ) value);
    }

}
