//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for WindowStateType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WindowStateType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="closed"/>
 *     &lt;enumeration value="minimized"/>
 *     &lt;enumeration value="maximized"/>
 *     &lt;enumeration value="normal"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum WindowStateType {

    @XmlEnumValue("closed")
    CLOSED("closed"),
    @XmlEnumValue("minimized")
    MINIMIZED("minimized"),
    @XmlEnumValue("maximized")
    MAXIMIZED("maximized"),
    @XmlEnumValue("normal")
    NORMAL("normal");
    private final String value;

    WindowStateType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WindowStateType fromValue(String v) {
        for (WindowStateType c: WindowStateType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
