//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * 
 * 				concrete data adapter for WMS. Beside general service adapter parameter value for featureCount parameter
 * 				performing GetFeatureInfo requests can be defined
 * 			
 * 
 * <p>Java class for WMSGridCoverageAdapterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WMSGridCoverageAdapterType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/settings}ServiceAdapterType">
 *       &lt;sequence>
 *         &lt;element name="featureCount">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="changeable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="val" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WMSGridCoverageAdapterType", namespace = "http://www.deegree.org/settings", propOrder = {
    "featureCount"
})
public class WMSGridCoverageAdapterType
    extends ServiceAdapterType
{

    @XmlElement(namespace = "http://www.deegree.org/settings", required = true, nillable = true)
    protected WMSGridCoverageAdapterType.FeatureCount featureCount;

    /**
     * Gets the value of the featureCount property.
     * 
     * @return
     *     possible object is
     *     {@link WMSGridCoverageAdapterType.FeatureCount }
     *     
     */
    public WMSGridCoverageAdapterType.FeatureCount getFeatureCount() {
        return featureCount;
    }

    /**
     * Sets the value of the featureCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link WMSGridCoverageAdapterType.FeatureCount }
     *     
     */
    public void setFeatureCount(WMSGridCoverageAdapterType.FeatureCount value) {
        this.featureCount = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="changeable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *       &lt;attribute name="val" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class FeatureCount {

        @XmlValue
        protected String value;
        @XmlAttribute
        protected Boolean changeable;
        @XmlAttribute
        protected Integer val;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the changeable property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isChangeable() {
            if (changeable == null) {
                return false;
            } else {
                return changeable;
            }
        }

        /**
         * Sets the value of the changeable property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setChangeable(Boolean value) {
            this.changeable = value;
        }

        /**
         * Gets the value of the val property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getVal() {
            if (val == null) {
                return  1;
            } else {
                return val;
            }
        }

        /**
         * Sets the value of the val property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setVal(Integer value) {
            this.val = value;
        }

    }

}
