//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				This will be extend by most types. It enables setting if a user is allowed to changed a value of a setting-parameter
 * 			
 * 
 * <p>Java class for _ChangeableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_ChangeableType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="changeable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_ChangeableType", namespace = "http://www.deegree.org/settings")
@XmlSeeAlso({
    GraphicsType.class,
    SnapLayerType.class,
    FileAccessType.class,
    GeometryTypeType.class,
    WFSDefaultStyleType.class,
    FormatsType.class,
    ProjectTemplatesType.class,
    GeometryTopologyType.class,
    SecurityType.class,
    GeometryMetricsType.class,
    DatabaseDriversType.class,
    MapHandlingType.class,
    CursorDefinitionsType.class,
    ExternalReferencesType.class,
    FileFilterType.class,
    DictionariesType.class,
    DigitizingOptionsType.class,
    DataAdapterType.class
})
public abstract class _ChangeableType {

    @XmlAttribute
    protected Boolean changeable;

    /**
     * Gets the value of the changeable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isChangeable() {
        if (changeable == null) {
            return true;
        } else {
            return changeable;
        }
    }

    /**
     * Sets the value of the changeable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChangeable(Boolean value) {
        this.changeable = value;
    }

}
