//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for BorderPositionValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BorderPositionValueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="west"/>
 *     &lt;enumeration value="east"/>
 *     &lt;enumeration value="south"/>
 *     &lt;enumeration value="north"/>
 *     &lt;enumeration value="center"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum BorderPositionValueType {

    @XmlEnumValue("west")
    WEST("west"),
    @XmlEnumValue("east")
    EAST("east"),
    @XmlEnumValue("south")
    SOUTH("south"),
    @XmlEnumValue("north")
    NORTH("north"),
    @XmlEnumValue("center")
    CENTER("center");
    private final String value;

    BorderPositionValueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BorderPositionValueType fromValue(String v) {
        for (BorderPositionValueType c: BorderPositionValueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
