//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatasourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatasourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.deegree.org/coremapmodel}AbstractDatasource"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatasourceType", namespace = "http://www.deegree.org/coremapmodel", propOrder = {
    "abstractDatasource"
})
public class DatasourceType {

    @XmlElementRef(name = "AbstractDatasource", namespace = "http://www.deegree.org/coremapmodel", type = JAXBElement.class)
    protected JAXBElement<? extends AbstractDatasourceType> abstractDatasource;

    /**
     * Gets the value of the abstractDatasource property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ServiceDatasourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link WFSDatasourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DatabaseDatasourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractDatasourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link WCSDatasourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link WMSDatasourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MemoryDatasourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FileDatasourceType }{@code >}
     *     
     */
    public JAXBElement<? extends AbstractDatasourceType> getAbstractDatasource() {
        return abstractDatasource;
    }

    /**
     * Sets the value of the abstractDatasource property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ServiceDatasourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link WFSDatasourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DatabaseDatasourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractDatasourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link WCSDatasourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link WMSDatasourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MemoryDatasourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FileDatasourceType }{@code >}
     *     
     */
    public void setAbstractDatasource(JAXBElement<? extends AbstractDatasourceType> value) {
        this.abstractDatasource = ((JAXBElement<? extends AbstractDatasourceType> ) value);
    }

}
