//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.29 at 09:58:26 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			A 	DefinedStyle is more or less the same as a NamedStyle but it identifies not an external style (known by a WMS)
 * 			but an internal style known by the application.
 * 			
 * 
 * <p>Java class for DefinedStyleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DefinedStyleType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/coremapmodel}NamedStyleType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="uom" type="{http://www.w3.org/2001/XMLSchema}string" default="pixel" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DefinedStyleType", namespace = "http://www.deegree.org/coremapmodel")
@XmlSeeAlso({
    ReferencedStyleType.class,
    DirectStyleType.class
})
public class DefinedStyleType
    extends NamedStyleType
{

    @XmlAttribute
    protected String uom;

    /**
     * Gets the value of the uom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUom() {
        if (uom == null) {
            return "pixel";
        } else {
            return uom;
        }
    }

    /**
     * Sets the value of the uom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUom(String value) {
        this.uom = value;
    }

}
