//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeometryTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeometryTypeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/settings}_ChangeableType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="allowPoints" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="allowLinestrings" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="allowPolygons" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="allowMultiPoints" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="allowMultiLinestrings" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="allowMultiPolygons" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="allowHoles" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="allowGeometryCollections" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="allowNoneLinearInterpolation" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeometryTypeType", namespace = "http://www.deegree.org/settings")
public class GeometryTypeType
    extends _ChangeableType
{

    @XmlAttribute
    protected Boolean allowPoints;
    @XmlAttribute
    protected Boolean allowLinestrings;
    @XmlAttribute
    protected Boolean allowPolygons;
    @XmlAttribute
    protected Boolean allowMultiPoints;
    @XmlAttribute
    protected Boolean allowMultiLinestrings;
    @XmlAttribute
    protected Boolean allowMultiPolygons;
    @XmlAttribute
    protected Boolean allowHoles;
    @XmlAttribute
    protected Boolean allowGeometryCollections;
    @XmlAttribute
    protected Boolean allowNoneLinearInterpolation;

    /**
     * Gets the value of the allowPoints property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowPoints() {
        if (allowPoints == null) {
            return true;
        } else {
            return allowPoints;
        }
    }

    /**
     * Sets the value of the allowPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowPoints(Boolean value) {
        this.allowPoints = value;
    }

    /**
     * Gets the value of the allowLinestrings property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowLinestrings() {
        if (allowLinestrings == null) {
            return true;
        } else {
            return allowLinestrings;
        }
    }

    /**
     * Sets the value of the allowLinestrings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowLinestrings(Boolean value) {
        this.allowLinestrings = value;
    }

    /**
     * Gets the value of the allowPolygons property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowPolygons() {
        if (allowPolygons == null) {
            return true;
        } else {
            return allowPolygons;
        }
    }

    /**
     * Sets the value of the allowPolygons property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowPolygons(Boolean value) {
        this.allowPolygons = value;
    }

    /**
     * Gets the value of the allowMultiPoints property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowMultiPoints() {
        if (allowMultiPoints == null) {
            return true;
        } else {
            return allowMultiPoints;
        }
    }

    /**
     * Sets the value of the allowMultiPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowMultiPoints(Boolean value) {
        this.allowMultiPoints = value;
    }

    /**
     * Gets the value of the allowMultiLinestrings property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowMultiLinestrings() {
        if (allowMultiLinestrings == null) {
            return true;
        } else {
            return allowMultiLinestrings;
        }
    }

    /**
     * Sets the value of the allowMultiLinestrings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowMultiLinestrings(Boolean value) {
        this.allowMultiLinestrings = value;
    }

    /**
     * Gets the value of the allowMultiPolygons property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowMultiPolygons() {
        if (allowMultiPolygons == null) {
            return true;
        } else {
            return allowMultiPolygons;
        }
    }

    /**
     * Sets the value of the allowMultiPolygons property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowMultiPolygons(Boolean value) {
        this.allowMultiPolygons = value;
    }

    /**
     * Gets the value of the allowHoles property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowHoles() {
        if (allowHoles == null) {
            return true;
        } else {
            return allowHoles;
        }
    }

    /**
     * Sets the value of the allowHoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowHoles(Boolean value) {
        this.allowHoles = value;
    }

    /**
     * Gets the value of the allowGeometryCollections property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowGeometryCollections() {
        if (allowGeometryCollections == null) {
            return false;
        } else {
            return allowGeometryCollections;
        }
    }

    /**
     * Sets the value of the allowGeometryCollections property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowGeometryCollections(Boolean value) {
        this.allowGeometryCollections = value;
    }

    /**
     * Gets the value of the allowNoneLinearInterpolation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowNoneLinearInterpolation() {
        if (allowNoneLinearInterpolation == null) {
            return false;
        } else {
            return allowNoneLinearInterpolation;
        }
    }

    /**
     * Sets the value of the allowNoneLinearInterpolation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowNoneLinearInterpolation(Boolean value) {
        this.allowNoneLinearInterpolation = value;
    }

}
