//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeometryMetricsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeometryMetricsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/settings}_ChangeableType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="checkForValidGeometries" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="disallowRepeatedPoints" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="checkForPolygonOrientation" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="disallowDoubleGeomerties" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="minSegmentLength" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="minSegmentLengthValue" type="{http://www.w3.org/2001/XMLSchema}float" default="0.001" />
 *       &lt;attribute name="ensureSimpleLines" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="minPolygonArea" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="minPolygonAreaValue" type="{http://www.w3.org/2001/XMLSchema}float" default="0.01" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeometryMetricsType", namespace = "http://www.deegree.org/settings")
public class GeometryMetricsType
    extends _ChangeableType
{

    @XmlAttribute
    protected Boolean checkForValidGeometries;
    @XmlAttribute
    protected Boolean disallowRepeatedPoints;
    @XmlAttribute
    protected Boolean checkForPolygonOrientation;
    @XmlAttribute
    protected Boolean disallowDoubleGeomerties;
    @XmlAttribute
    protected Boolean minSegmentLength;
    @XmlAttribute
    protected Float minSegmentLengthValue;
    @XmlAttribute
    protected Boolean ensureSimpleLines;
    @XmlAttribute
    protected Boolean minPolygonArea;
    @XmlAttribute
    protected Float minPolygonAreaValue;

    /**
     * Gets the value of the checkForValidGeometries property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCheckForValidGeometries() {
        if (checkForValidGeometries == null) {
            return true;
        } else {
            return checkForValidGeometries;
        }
    }

    /**
     * Sets the value of the checkForValidGeometries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCheckForValidGeometries(Boolean value) {
        this.checkForValidGeometries = value;
    }

    /**
     * Gets the value of the disallowRepeatedPoints property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDisallowRepeatedPoints() {
        if (disallowRepeatedPoints == null) {
            return true;
        } else {
            return disallowRepeatedPoints;
        }
    }

    /**
     * Sets the value of the disallowRepeatedPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisallowRepeatedPoints(Boolean value) {
        this.disallowRepeatedPoints = value;
    }

    /**
     * Gets the value of the checkForPolygonOrientation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCheckForPolygonOrientation() {
        if (checkForPolygonOrientation == null) {
            return true;
        } else {
            return checkForPolygonOrientation;
        }
    }

    /**
     * Sets the value of the checkForPolygonOrientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCheckForPolygonOrientation(Boolean value) {
        this.checkForPolygonOrientation = value;
    }

    /**
     * Gets the value of the disallowDoubleGeomerties property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDisallowDoubleGeomerties() {
        if (disallowDoubleGeomerties == null) {
            return true;
        } else {
            return disallowDoubleGeomerties;
        }
    }

    /**
     * Sets the value of the disallowDoubleGeomerties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisallowDoubleGeomerties(Boolean value) {
        this.disallowDoubleGeomerties = value;
    }

    /**
     * Gets the value of the minSegmentLength property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMinSegmentLength() {
        if (minSegmentLength == null) {
            return false;
        } else {
            return minSegmentLength;
        }
    }

    /**
     * Sets the value of the minSegmentLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMinSegmentLength(Boolean value) {
        this.minSegmentLength = value;
    }

    /**
     * Gets the value of the minSegmentLengthValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getMinSegmentLengthValue() {
        if (minSegmentLengthValue == null) {
            return  0.0010F;
        } else {
            return minSegmentLengthValue;
        }
    }

    /**
     * Sets the value of the minSegmentLengthValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMinSegmentLengthValue(Float value) {
        this.minSegmentLengthValue = value;
    }

    /**
     * Gets the value of the ensureSimpleLines property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEnsureSimpleLines() {
        if (ensureSimpleLines == null) {
            return false;
        } else {
            return ensureSimpleLines;
        }
    }

    /**
     * Sets the value of the ensureSimpleLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnsureSimpleLines(Boolean value) {
        this.ensureSimpleLines = value;
    }

    /**
     * Gets the value of the minPolygonArea property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMinPolygonArea() {
        if (minPolygonArea == null) {
            return false;
        } else {
            return minPolygonArea;
        }
    }

    /**
     * Sets the value of the minPolygonArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMinPolygonArea(Boolean value) {
        this.minPolygonArea = value;
    }

    /**
     * Gets the value of the minPolygonAreaValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getMinPolygonAreaValue() {
        if (minPolygonAreaValue == null) {
            return  0.01F;
        } else {
            return minPolygonAreaValue;
        }
    }

    /**
     * Sets the value of the minPolygonAreaValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMinPolygonAreaValue(Float value) {
        this.minPolygonAreaValue = value;
    }

}
