//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Collects user specific settings around SLD and the StyleEditor (ClassificationPreset and StylePreset are not used, yet). 
 * 			
 * 
 * <p>Java class for GraphicsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GraphicsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/settings}_ChangeableType">
 *       &lt;sequence>
 *         &lt;element name="SymbolDefinitions" type="{http://www.deegree.org/settings}GraphicDefinitionsType" minOccurs="0"/>
 *         &lt;element name="FillGraphicDefinitions" type="{http://www.deegree.org/settings}GraphicDefinitionsType" minOccurs="0"/>
 *         &lt;element name="DashArrayDefinitions" type="{http://www.deegree.org/settings}DashArrayDefinitionsType" minOccurs="0"/>
 *         &lt;element name="ClassificationPreset" type="{http://www.deegree.org/settings}PresetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StylePreset" type="{http://www.deegree.org/settings}PresetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SymbolizerPreset" type="{http://www.deegree.org/settings}PresetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ColorSchemes" type="{http://www.deegree.org/settings}ColorSchemesType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GraphicsType", namespace = "http://www.deegree.org/settings", propOrder = {
    "symbolDefinitions",
    "fillGraphicDefinitions",
    "dashArrayDefinitions",
    "classificationPreset",
    "stylePreset",
    "symbolizerPreset",
    "colorSchemes"
})
public class GraphicsType
    extends _ChangeableType
{

    @XmlElement(name = "SymbolDefinitions", namespace = "http://www.deegree.org/settings")
    protected GraphicDefinitionsType symbolDefinitions;
    @XmlElement(name = "FillGraphicDefinitions", namespace = "http://www.deegree.org/settings")
    protected GraphicDefinitionsType fillGraphicDefinitions;
    @XmlElement(name = "DashArrayDefinitions", namespace = "http://www.deegree.org/settings")
    protected DashArrayDefinitionsType dashArrayDefinitions;
    @XmlElement(name = "ClassificationPreset", namespace = "http://www.deegree.org/settings")
    protected List<PresetType> classificationPreset;
    @XmlElement(name = "StylePreset", namespace = "http://www.deegree.org/settings")
    protected List<PresetType> stylePreset;
    @XmlElement(name = "SymbolizerPreset", namespace = "http://www.deegree.org/settings")
    protected List<PresetType> symbolizerPreset;
    @XmlElement(name = "ColorSchemes", namespace = "http://www.deegree.org/settings")
    protected List<ColorSchemesType> colorSchemes;

    /**
     * Gets the value of the symbolDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link GraphicDefinitionsType }
     *     
     */
    public GraphicDefinitionsType getSymbolDefinitions() {
        return symbolDefinitions;
    }

    /**
     * Sets the value of the symbolDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link GraphicDefinitionsType }
     *     
     */
    public void setSymbolDefinitions(GraphicDefinitionsType value) {
        this.symbolDefinitions = value;
    }

    /**
     * Gets the value of the fillGraphicDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link GraphicDefinitionsType }
     *     
     */
    public GraphicDefinitionsType getFillGraphicDefinitions() {
        return fillGraphicDefinitions;
    }

    /**
     * Sets the value of the fillGraphicDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link GraphicDefinitionsType }
     *     
     */
    public void setFillGraphicDefinitions(GraphicDefinitionsType value) {
        this.fillGraphicDefinitions = value;
    }

    /**
     * Gets the value of the dashArrayDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link DashArrayDefinitionsType }
     *     
     */
    public DashArrayDefinitionsType getDashArrayDefinitions() {
        return dashArrayDefinitions;
    }

    /**
     * Sets the value of the dashArrayDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DashArrayDefinitionsType }
     *     
     */
    public void setDashArrayDefinitions(DashArrayDefinitionsType value) {
        this.dashArrayDefinitions = value;
    }

    /**
     * Gets the value of the classificationPreset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classificationPreset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassificationPreset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PresetType }
     * 
     * 
     */
    public List<PresetType> getClassificationPreset() {
        if (classificationPreset == null) {
            classificationPreset = new ArrayList<PresetType>();
        }
        return this.classificationPreset;
    }

    /**
     * Gets the value of the stylePreset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stylePreset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStylePreset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PresetType }
     * 
     * 
     */
    public List<PresetType> getStylePreset() {
        if (stylePreset == null) {
            stylePreset = new ArrayList<PresetType>();
        }
        return this.stylePreset;
    }

    /**
     * Gets the value of the symbolizerPreset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the symbolizerPreset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSymbolizerPreset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PresetType }
     * 
     * 
     */
    public List<PresetType> getSymbolizerPreset() {
        if (symbolizerPreset == null) {
            symbolizerPreset = new ArrayList<PresetType>();
        }
        return this.symbolizerPreset;
    }

    /**
     * Gets the value of the colorSchemes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the colorSchemes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColorSchemes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ColorSchemesType }
     * 
     * 
     */
    public List<ColorSchemesType> getColorSchemes() {
        if (colorSchemes == null) {
            colorSchemes = new ArrayList<ColorSchemesType>();
        }
        return this.colorSchemes;
    }

}
