//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				In a GridLayout compones can be organzied in Columns and Rows. Each column can have a different amount of rows.
 * 				Each row can have a different height; each column can have a different width
 * 			
 * 
 * <p>Java class for GridLayoutType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GridLayoutType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/project}_AbstractLayoutType">
 *       &lt;sequence>
 *         &lt;element name="rows" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cols" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GridLayoutType", propOrder = {
    "rows",
    "cols"
})
public class GridLayoutType
    extends _AbstractLayoutType
{

    protected int rows;
    protected int cols;

    /**
     * Gets the value of the rows property.
     * 
     */
    public int getRows() {
        return rows;
    }

    /**
     * Sets the value of the rows property.
     * 
     */
    public void setRows(int value) {
        this.rows = value;
    }

    /**
     * Gets the value of the cols property.
     * 
     */
    public int getCols() {
        return cols;
    }

    /**
     * Sets the value of the cols property.
     * 
     */
    public void setCols(int value) {
        this.cols = value;
    }

}
