//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * 
 * 				Here the procentual change of map extension for zoom and pan operations is defined
 * 			
 * 
 * <p>Java class for MapHandlingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MapHandlingType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/settings}_ChangeableType">
 *       &lt;sequence>
 *         &lt;element name="zoomLevel">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="val" type="{http://www.w3.org/2001/XMLSchema}float" default="25" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="panLevel">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="val" type="{http://www.w3.org/2001/XMLSchema}float" default="25" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MapHandlingType", namespace = "http://www.deegree.org/settings", propOrder = {
    "zoomLevel",
    "panLevel"
})
public class MapHandlingType
    extends _ChangeableType
{

    @XmlElement(namespace = "http://www.deegree.org/settings", required = true)
    protected MapHandlingType.ZoomLevel zoomLevel;
    @XmlElement(namespace = "http://www.deegree.org/settings", required = true)
    protected MapHandlingType.PanLevel panLevel;

    /**
     * Gets the value of the zoomLevel property.
     * 
     * @return
     *     possible object is
     *     {@link MapHandlingType.ZoomLevel }
     *     
     */
    public MapHandlingType.ZoomLevel getZoomLevel() {
        return zoomLevel;
    }

    /**
     * Sets the value of the zoomLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapHandlingType.ZoomLevel }
     *     
     */
    public void setZoomLevel(MapHandlingType.ZoomLevel value) {
        this.zoomLevel = value;
    }

    /**
     * Gets the value of the panLevel property.
     * 
     * @return
     *     possible object is
     *     {@link MapHandlingType.PanLevel }
     *     
     */
    public MapHandlingType.PanLevel getPanLevel() {
        return panLevel;
    }

    /**
     * Sets the value of the panLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapHandlingType.PanLevel }
     *     
     */
    public void setPanLevel(MapHandlingType.PanLevel value) {
        this.panLevel = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="val" type="{http://www.w3.org/2001/XMLSchema}float" default="25" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PanLevel {

        @XmlValue
        protected String value;
        @XmlAttribute
        protected Float val;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the val property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public float getVal() {
            if (val == null) {
                return  25.0F;
            } else {
                return val;
            }
        }

        /**
         * Sets the value of the val property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setVal(Float value) {
            this.val = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="val" type="{http://www.w3.org/2001/XMLSchema}float" default="25" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ZoomLevel {

        @XmlValue
        protected String value;
        @XmlAttribute
        protected Float val;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the val property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public float getVal() {
            if (val == null) {
                return  25.0F;
            } else {
                return val;
            }
        }

        /**
         * Sets the value of the val property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setVal(Float value) {
            this.val = value;
        }

    }

}
