//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				A MapModel defines the content of a map and its description. Major part if a list of layers/layergroups that are arragned 
 * 				in a tree. beside name and unique identifier a map model contains a description of the target device it will be displayed on,
 * 				a (current) spatial extent and a maximum valid spatial extent. As a MapModelCollection a MapModel may also has references
 * 				to external resources.
 * 			
 * 
 * <p>Java class for MapModelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MapModelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.deegree.org/coremapmodel}identifier"/>
 *         &lt;element ref="{http://www.deegree.org/coremapmodel}targetDevice"/>
 *         &lt;element name="supportedCRS" type="{http://www.deegree.org/coremapmodel}supportedCRSType" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/coremapmodel}extent"/>
 *         &lt;element ref="{http://www.deegree.org/coremapmodel}maxExtent"/>
 *         &lt;element name="layerGroup" type="{http://www.deegree.org/coremapmodel}LayerGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/coremapmodel}externalResource" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="current" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MapModelType", namespace = "http://www.deegree.org/coremapmodel", propOrder = {
    "name",
    "identifier",
    "targetDevice",
    "supportedCRS",
    "extent",
    "maxExtent",
    "layerGroup",
    "externalResource",
    "description"
})
public class MapModelType {

    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected String name;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected IdentifierType identifier;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected TargetDeviceType targetDevice;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel")
    protected SupportedCRSType supportedCRS;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected EnvelopeType extent;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected EnvelopeType maxExtent;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel")
    protected List<LayerGroupType> layerGroup;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel")
    protected List<ExternalResourceType> externalResource;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel")
    protected String description;
    @XmlAttribute
    protected Boolean current;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setIdentifier(IdentifierType value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the targetDevice property.
     * 
     * @return
     *     possible object is
     *     {@link TargetDeviceType }
     *     
     */
    public TargetDeviceType getTargetDevice() {
        return targetDevice;
    }

    /**
     * Sets the value of the targetDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetDeviceType }
     *     
     */
    public void setTargetDevice(TargetDeviceType value) {
        this.targetDevice = value;
    }

    /**
     * Gets the value of the supportedCRS property.
     * 
     * @return
     *     possible object is
     *     {@link SupportedCRSType }
     *     
     */
    public SupportedCRSType getSupportedCRS() {
        return supportedCRS;
    }

    /**
     * Sets the value of the supportedCRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportedCRSType }
     *     
     */
    public void setSupportedCRS(SupportedCRSType value) {
        this.supportedCRS = value;
    }

    /**
     * Gets the value of the extent property.
     * 
     * @return
     *     possible object is
     *     {@link EnvelopeType }
     *     
     */
    public EnvelopeType getExtent() {
        return extent;
    }

    /**
     * Sets the value of the extent property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnvelopeType }
     *     
     */
    public void setExtent(EnvelopeType value) {
        this.extent = value;
    }

    /**
     * Gets the value of the maxExtent property.
     * 
     * @return
     *     possible object is
     *     {@link EnvelopeType }
     *     
     */
    public EnvelopeType getMaxExtent() {
        return maxExtent;
    }

    /**
     * Sets the value of the maxExtent property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnvelopeType }
     *     
     */
    public void setMaxExtent(EnvelopeType value) {
        this.maxExtent = value;
    }

    /**
     * Gets the value of the layerGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the layerGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLayerGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LayerGroupType }
     * 
     * 
     */
    public List<LayerGroupType> getLayerGroup() {
        if (layerGroup == null) {
            layerGroup = new ArrayList<LayerGroupType>();
        }
        return this.layerGroup;
    }

    /**
     * Gets the value of the externalResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalResourceType }
     * 
     * 
     */
    public List<ExternalResourceType> getExternalResource() {
        if (externalResource == null) {
            externalResource = new ArrayList<ExternalResourceType>();
        }
        return this.externalResource;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the current property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCurrent() {
        if (current == null) {
            return false;
        } else {
            return current;
        }
    }

    /**
     * Sets the value of the current property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCurrent(Boolean value) {
        this.current = value;
    }

}
