//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			Available functions within a project and their layout arrangment are defined by modules registered to a project. First modules must have a 
 * 			name and a unique identifier.
 * 			- the name of the java class realizing a module must be defined be element className. This enable registering modules that are not part of
 * 			  deegree, just the Module interface from deegree iGeoDesktop must be implemented.
 * 			- a module may also have a description explaining a few detailes on its functionality
 * 			- like a project itself each modul must define its viewform. This means it must define its visual representation 
 * 			- Each module may register eintries to menubar, toolbar and popmenu as defined for a project
 * 			- A module may have different states according to the application. A state has a name and a set of parameters. It may be used to store processing
 * 			  states if a projected it stored and closed before the function/process realized by a moduled has been finished.
 * 			- Each module may offeres it own help. The registered fragments (html-pages) are included into application/project help when a module is loaded.
 * 			- Finaly a module may has some init-parameter to define further configuration informations like URLs, timeouts, sizes etc.
 * 		
 * 
 * <p>Java class for ModuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModuleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.deegree.org/coremapmodel}identifier"/>
 *         &lt;element name="className" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.deegree.org/project}ViewForm"/>
 *         &lt;element ref="{http://www.deegree.org/project}Menu" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/project}PopUpEntry" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/project}ToolBarEntry" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/project}ApplicationState" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/settings}HelpContext" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="init-param" type="{http://www.deegree.org/project}ParameterType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModuleType", propOrder = {
    "name",
    "identifier",
    "className",
    "viewForm",
    "menu",
    "popUpEntry",
    "toolBarEntry",
    "applicationState",
    "helpContext",
    "initParam"
})
@XmlSeeAlso({
    ModuleGroupType.class
})
public class ModuleType {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected IdentifierType identifier;
    @XmlElement(required = true)
    protected String className;
    @XmlElement(name = "ViewForm", required = true)
    protected ViewFormType viewForm;
    @XmlElement(name = "Menu")
    protected List<MenuType> menu;
    @XmlElement(name = "PopUpEntry")
    protected List<PopUpEntryType> popUpEntry;
    @XmlElement(name = "ToolBarEntry")
    protected List<ToolbarEntryType> toolBarEntry;
    @XmlElement(name = "ApplicationState")
    protected List<ApplicationStateType> applicationState;
    @XmlElement(name = "HelpContext", namespace = "http://www.deegree.org/settings")
    protected List<HelpContextType> helpContext;
    @XmlElement(name = "init-param")
    protected List<ParameterType> initParam;
    @XmlAttribute
    protected Boolean visible;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setIdentifier(IdentifierType value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the viewForm property.
     * 
     * @return
     *     possible object is
     *     {@link ViewFormType }
     *     
     */
    public ViewFormType getViewForm() {
        return viewForm;
    }

    /**
     * Sets the value of the viewForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewFormType }
     *     
     */
    public void setViewForm(ViewFormType value) {
        this.viewForm = value;
    }

    /**
     * Gets the value of the menu property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the menu property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMenu().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MenuType }
     * 
     * 
     */
    public List<MenuType> getMenu() {
        if (menu == null) {
            menu = new ArrayList<MenuType>();
        }
        return this.menu;
    }

    /**
     * Gets the value of the popUpEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the popUpEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPopUpEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PopUpEntryType }
     * 
     * 
     */
    public List<PopUpEntryType> getPopUpEntry() {
        if (popUpEntry == null) {
            popUpEntry = new ArrayList<PopUpEntryType>();
        }
        return this.popUpEntry;
    }

    /**
     * Gets the value of the toolBarEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toolBarEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToolBarEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ToolbarEntryType }
     * 
     * 
     */
    public List<ToolbarEntryType> getToolBarEntry() {
        if (toolBarEntry == null) {
            toolBarEntry = new ArrayList<ToolbarEntryType>();
        }
        return this.toolBarEntry;
    }

    /**
     * Gets the value of the applicationState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationStateType }
     * 
     * 
     */
    public List<ApplicationStateType> getApplicationState() {
        if (applicationState == null) {
            applicationState = new ArrayList<ApplicationStateType>();
        }
        return this.applicationState;
    }

    /**
     * Gets the value of the helpContext property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the helpContext property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHelpContext().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HelpContextType }
     * 
     * 
     */
    public List<HelpContextType> getHelpContext() {
        if (helpContext == null) {
            helpContext = new ArrayList<HelpContextType>();
        }
        return this.helpContext;
    }

    /**
     * Gets the value of the initParam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the initParam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInitParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterType }
     * 
     * 
     */
    public List<ParameterType> getInitParam() {
        if (initParam == null) {
            initParam = new ArrayList<ParameterType>();
        }
        return this.initParam;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isVisible() {
        if (visible == null) {
            return true;
        } else {
            return visible;
        }
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisible(Boolean value) {
        this.visible = value;
    }

}
