//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				featureProperty must be something like: {http://www.deegree.org/app}:myProperty
 * 				table column is just the name of a column of the linked table (not case sensitive)
 * 			
 * 
 * <p>Java class for RelationKeyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelationKeyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="featureProperty" type="{http://www.deegree.org/coremapmodel}QualifiedNameType"/>
 *         &lt;element name="tableColumn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelationKeyType", namespace = "http://www.deegree.org/coremapmodel", propOrder = {
    "featureProperty",
    "tableColumn"
})
public class RelationKeyType {

    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected QualifiedNameType featureProperty;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected String tableColumn;

    /**
     * Gets the value of the featureProperty property.
     * 
     * @return
     *     possible object is
     *     {@link QualifiedNameType }
     *     
     */
    public QualifiedNameType getFeatureProperty() {
        return featureProperty;
    }

    /**
     * Sets the value of the featureProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualifiedNameType }
     *     
     */
    public void setFeatureProperty(QualifiedNameType value) {
        this.featureProperty = value;
    }

    /**
     * Gets the value of the tableColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableColumn() {
        return tableColumn;
    }

    /**
     * Sets the value of the tableColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableColumn(String value) {
        this.tableColumn = value;
    }

}
