//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 10:29:06 AM MESZ 
//


package org.deegree.igeo.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * 
 * 				Settings for snapping operation. Using this element it can be defined which layers will be target for snapping
 * 				and what's the snapping distance (radius aroud mouse cursor). Also it can be defined which unit of measure
 * 				will be used for defining snapping distance (metre and pixel are valid values)
 * 			
 * 
 * <p>Java class for SnappingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SnappingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tolerance">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="uom" type="{http://www.w3.org/2001/XMLSchema}string" default="Pixel" />
 *                 &lt;attribute name="val" type="{http://www.w3.org/2001/XMLSchema}float" default="20" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="snapLayer" type="{http://www.deegree.org/settings}SnapLayerType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SnappingType", namespace = "http://www.deegree.org/settings", propOrder = {
    "tolerance",
    "snapLayer"
})
public class SnappingType {

    @XmlElement(namespace = "http://www.deegree.org/settings", required = true)
    protected SnappingType.Tolerance tolerance;
    @XmlElement(namespace = "http://www.deegree.org/settings")
    protected List<SnapLayerType> snapLayer;

    /**
     * Gets the value of the tolerance property.
     * 
     * @return
     *     possible object is
     *     {@link SnappingType.Tolerance }
     *     
     */
    public SnappingType.Tolerance getTolerance() {
        return tolerance;
    }

    /**
     * Sets the value of the tolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link SnappingType.Tolerance }
     *     
     */
    public void setTolerance(SnappingType.Tolerance value) {
        this.tolerance = value;
    }

    /**
     * Gets the value of the snapLayer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the snapLayer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSnapLayer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SnapLayerType }
     * 
     * 
     */
    public List<SnapLayerType> getSnapLayer() {
        if (snapLayer == null) {
            snapLayer = new ArrayList<SnapLayerType>();
        }
        return this.snapLayer;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="uom" type="{http://www.w3.org/2001/XMLSchema}string" default="Pixel" />
     *       &lt;attribute name="val" type="{http://www.w3.org/2001/XMLSchema}float" default="20" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Tolerance {

        @XmlValue
        protected String value;
        @XmlAttribute
        protected String uom;
        @XmlAttribute
        protected Float val;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the uom property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUom() {
            if (uom == null) {
                return "Pixel";
            } else {
                return uom;
            }
        }

        /**
         * Sets the value of the uom property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUom(String value) {
            this.uom = value;
        }

        /**
         * Gets the value of the val property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public float getVal() {
            if (val == null) {
                return  20.0F;
            } else {
                return val;
            }
        }

        /**
         * Sets the value of the val property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setVal(Float value) {
            this.val = value;
        }

    }

}
