//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.17 at 04:56:00 PM MESZ 
//


package org.deegree.igeo.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Datasource for accessing an OGC Web Coverage service. Similiar to database datasource a template must be
 * 				defined for accessing data. In case of a WCS datasource this must be a GetCoverage request without URL,
 * 				 boundingbox, width, height and CRS. Both parameters will be added by iGeoDesktop when requesting data.
 * 			
 * 
 * <p>Java class for WCSDatasourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WCSDatasourceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/coremapmodel}ServiceDatasourceType">
 *       &lt;sequence>
 *         &lt;element name="coverage" type="{http://www.deegree.org/coremapmodel}QualifiedNameType"/>
 *         &lt;element name="format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WCSDatasourceType", namespace = "http://www.deegree.org/coremapmodel", propOrder = {
    "coverage",
    "format",
    "time"
})
public class WCSDatasourceType
    extends ServiceDatasourceType
{

    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected QualifiedNameType coverage;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel", required = true)
    protected String format;
    @XmlElement(namespace = "http://www.deegree.org/coremapmodel")
    protected String time;

    /**
     * Gets the value of the coverage property.
     * 
     * @return
     *     possible object is
     *     {@link QualifiedNameType }
     *     
     */
    public QualifiedNameType getCoverage() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualifiedNameType }
     *     
     */
    public void setCoverage(QualifiedNameType value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime(String value) {
        this.time = value;
    }

}
