//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.22 at 02:21:41 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.deegree.org/bookmarks", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.deegree.igeo.modules.bookmarks;
