//$HeadURL$
/*----------------------------------------------------------------------------
 This file is part of deegree, http://deegree.org/
 Copyright (C) 2001-2009 by:
 - Department of Geography, University of Bonn -
 and
 - lat/lon GmbH -

 This library is free software; you can redistribute it and/or modify it under
 the terms of the GNU Lesser General Public License as published by the Free
 Software Foundation; either version 2.1 of the License, or (at your option)
 any later version.
 This library is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 details.
 You should have received a copy of the GNU Lesser General Public License
 along with this library; if not, write to the Free Software Foundation, Inc.,
 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 Contact information:

 lat/lon GmbH
 Aennchenstr. 19, 53177 Bonn
 Germany
 http://lat-lon.de/

 Department of Geography, University of Bonn
 Prof. Dr. Klaus Greve
 Postfach 1147, 53001 Bonn
 Germany
 http://www.geographie.uni-bonn.de/deegree/

 e-mail: info@deegree.org
 ----------------------------------------------------------------------------*/
package org.deegree.igeo.mapmodel;

import java.util.List;

import org.deegree.igeo.config.LayerType;
import org.deegree.igeo.config.LayerType.MetadataURL;
import org.deegree.model.Identifier;

/**
 * An extension of the {@link Layer} for managing layers that has been generated by iGeodesktop containing
 * geo-information that does not have a real-world counterpart; for example: positions of topological errors of loaded
 * geometries.
 * 
 * @author <a href="mailto:name@deegree.org">Andreas Poth</a>
 * @author last edited by: $Author$
 * 
 * @version $Revision$, $Date$
 */
public class SystemLayer extends Layer {

    private boolean visibleInLayerTree = true;

    /**
     * @param layerType
     * @param owner
     * @param datasources
     * @param styles
     */
    public SystemLayer( LayerType layerType, MapModel owner, List<Datasource> datasources, List<NamedStyle> styles ) {
        super( layerType, owner, datasources, styles );
    }

    /**
     * @param owner
     * @param identifier
     * @param title
     * @param abstract1
     * @param datasources
     * @param metadataURLs
     */
    public SystemLayer( MapModel owner, Identifier identifier, String title, String abstract1,
                        List<Datasource> datasources, List<MetadataURL> metadataURLs ) {
        super( owner, identifier, title, abstract1, datasources, metadataURLs );
    }

    /**
     * @param owner
     * @param identifier
     * @param title
     * @param abstract1
     */
    public SystemLayer( MapModel owner, Identifier identifier, String title, String abstract1 ) {
        super( owner, identifier, title, abstract1 );
    }

    public void setVisibleInLayerTree( boolean b ) {
        this.visibleInLayerTree = b;
    }

    public boolean isVisibleInLayerTree() {
        return visibleInLayerTree;
    }

}
